/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversoralura;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Lissette
 */
public class Venata extends javax.swing.JFrame {

    /**
     * Creates new form Venata
     */
    private double cambioQuetzal = 1.0;
    private double cambioYen= 16.794963;
    private double cambioLibraEsterlina= 0.104349;
    private double cambioEuror= 0.11806207;
    private double cambiowonr= 164.59098;
    private double cambioDolar= 0.12848272;
    private final Double[] monedas={cambioQuetzal,cambiowonr,cambioYen,cambioLibraEsterlina,cambioEuror,cambioDolar};
    //private final javax.swing.JLabel[] labelMonedas = (quetzalLabel,yenLabel,libraLabel,euroLabel,wonLabel,dolarLabel);
    private final Double[] lengthList = {1.0,1000.00,0.001,3.2808399,39.3700787,0.00062137};
    private final javax.swing.JLabel[] listaMonedas,listaLongitud;
    private final SetCurrency setCurrencywindow;
    public Venata() {
        //this.labelMonedas = new javax.swing.JLabel[](quetzalLabel,yenLabel,libraLabel,euroLabel,wonLabel,dolarLabel);
        initComponents();
        this.listaMonedas = new JLabel[]{quetzalLabel,wonLabel,yenLabel,libraLabel,euroLabel,dolarLabel};
        this.listaLongitud = new JLabel[]{lengthMetroLabel,lengthMilimetroLabel,lengthKilometroLabel,lengthFootLabel,lengthInchoLabel,lengthMiileLabel};
        /*quetzalLabel.setText(Double.toString(cambioQuetzal));
        wonLabel.setText(Double.toString(cambiowonr));
        yenLabel.setText(Double.toString(cambioYen));
        libraLabel.setText(Double.toString(cambioLibraEsterlina));
        euroLabel.setText(Double.toString(cambioEuror));
        dolarLabel.setText(Double.toString(cambioDolar));*/
        llenarLabel(monedaTextArea,currencySelectorComboBox,monedas,listaMonedas);
        this.setCurrencywindow= new SetCurrency(monedas,this);
        currencySelectorComboBox.addActionListener((ae) -> {
            validarIngreso(monedaTextArea);
            llenarLabel(monedaTextArea,currencySelectorComboBox,monedas,listaMonedas);
        });
        
        llenarLabel(lengthTextArea, lengthComboBox, lengthList, listaLongitud);
        this.lengthComboBox.addActionListener((ae) -> {
            validarIngreso(lengthTextArea);
            llenarLabel(lengthTextArea, lengthComboBox, lengthList, listaLongitud);
        });
    }

    
    private Double aplicarConversion(Double base,Double currency){
        return(base*currency);
    }
    
    protected void llenarLabel(){
        llenarLabel(monedaTextArea,currencySelectorComboBox,monedas,listaMonedas);
    }
    
    protected void llenarLabel(JTextField textArea,JComboBox comboBox, Double[] RatesList, JLabel[] labelList){
        Double currency = Double.parseDouble(textArea.getText());
        int selectionCurrency=comboBox.getSelectedIndex();
        Double conversionActual;
        for(int i = 0; i<RatesList.length;i++){
            
            if(selectionCurrency==0){
                conversionActual = aplicarConversion(RatesList[i],currency);
                labelList[i].setText(conversionActual.toString());
            }
            else{
                //conversionActual = aplicarConversion(monedas[i],currency);
                Double quetzalBase=(aplicarConversion(1/RatesList[selectionCurrency], currency));
                labelList[0].setText(quetzalBase.toString());
                conversionActual=aplicarConversion(quetzalBase, RatesList[i]);
                labelList[i].setText(conversionActual.toString());
            }
            
        }
    }
    
    
    private void validarIngreso(JTextField textField){
        if(!this.setCurrencywindow.isNumeric(textField.getText())){
            JOptionPane.showMessageDialog(this, "Asegurese de ingresar sólo números");
            textField.setText("1");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        currencySelectorComboBox = new javax.swing.JComboBox<>();
        monedaTextArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dolarLabel = new javax.swing.JLabel();
        yenLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        euroLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        quetzalLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        libraLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        wonLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lengthTextArea = new javax.swing.JTextField();
        lengthComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lengthMetroLabel = new javax.swing.JLabel();
        lengthMilimetroLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lengthKilometroLabel = new javax.swing.JLabel();
        lengthFootLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lengthMiileLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lengthInchoLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        currencySet = new javax.swing.JMenuItem();
        exitMene = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        currencySelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quetzal", "Won sul-coreano", "Yen japonés", "Libra esterlina", "Euro", "Dólar" }));

        monedaTextArea.setText("1");
        monedaTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                monedaTextAreaKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Quetzal");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Yen Japonés");

        dolarLabel.setText("jLabel10");

        yenLabel.setText("jLabel4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Euros");

        euroLabel.setText("jLabel4");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Dolar");

        quetzalLabel.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Libras Esterlinas");

        libraLabel.setText("jLabel3");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Won Sul-coreano");

        wonLabel.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(monedaTextArea))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(wonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(libraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quetzalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(currencySelectorComboBox, 0, 137, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(euroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dolarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currencySelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monedaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yenLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(euroLabel)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dolarLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(quetzalLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(libraLabel)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wonLabel)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Moneda", jPanel1);

        lengthTextArea.setText("1");
        lengthTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lengthTextAreaKeyReleased(evt);
            }
        });

        lengthComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metro", "Milímetro", "Kilómetro", "Pie", "Pulgada", "Milla" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Metro");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Milímetro");

        lengthMetroLabel.setText("jLabel15");

        lengthMilimetroLabel.setText("jLabel16");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Pie");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Kilómetro");

        lengthKilometroLabel.setText("jLabel15");

        lengthFootLabel.setText("jLabel16");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Pulgada");

        lengthMiileLabel.setText("jLabel13");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Milla");

        lengthInchoLabel.setText("jLabel16");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lengthInchoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lengthMiileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lengthTextArea)
                                    .addComponent(lengthMetroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lengthKilometroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lengthComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lengthMilimetroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lengthFootLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthMetroLabel)
                    .addComponent(lengthMilimetroLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthKilometroLabel)
                    .addComponent(lengthFootLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthInchoLabel)
                    .addComponent(lengthMiileLabel))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Longitud", jPanel2);

        jMenu1.setText("Configuración");

        currencySet.setText("Factor de conversión");
        currencySet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                currencySetMousePressed(evt);
            }
        });
        jMenu1.add(currencySet);

        exitMene.setText("Salir");
        exitMene.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitMeneMouseReleased(evt);
            }
        });
        jMenu1.add(exitMene);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monedaTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monedaTextAreaKeyReleased
        // TODO add your handling code here:
        validarIngreso(monedaTextArea);
        llenarLabel(monedaTextArea,currencySelectorComboBox,monedas,listaMonedas);
    }//GEN-LAST:event_monedaTextAreaKeyReleased

    private void currencySetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currencySetMousePressed
        // TODO add your handling code here:
        this.setCurrencywindow.setVisible(true);
    }//GEN-LAST:event_currencySetMousePressed

    private void exitMeneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMeneMouseReleased
        System.exit(0);
    
    }//GEN-LAST:event_exitMeneMouseReleased

    private void lengthTextAreaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lengthTextAreaKeyReleased
        // TODO add your handling code here:
        validarIngreso(lengthTextArea);
        llenarLabel(lengthTextArea, lengthComboBox, lengthList, listaLongitud);
    }//GEN-LAST:event_lengthTextAreaKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venata().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> currencySelectorComboBox;
    private javax.swing.JMenuItem currencySet;
    private javax.swing.JLabel dolarLabel;
    private javax.swing.JLabel euroLabel;
    private javax.swing.JMenuItem exitMene;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> lengthComboBox;
    private javax.swing.JLabel lengthFootLabel;
    private javax.swing.JLabel lengthInchoLabel;
    private javax.swing.JLabel lengthKilometroLabel;
    private javax.swing.JLabel lengthMetroLabel;
    private javax.swing.JLabel lengthMiileLabel;
    private javax.swing.JLabel lengthMilimetroLabel;
    private javax.swing.JTextField lengthTextArea;
    private javax.swing.JLabel libraLabel;
    private javax.swing.JTextField monedaTextArea;
    private javax.swing.JLabel quetzalLabel;
    private javax.swing.JLabel wonLabel;
    private javax.swing.JLabel yenLabel;
    // End of variables declaration//GEN-END:variables
}
